// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Statistics;

namespace Statistics.Migrations
{
    [DbContext(typeof(StatisticContext))]
    [Migration("20230212182430_MachineIdentifier_Statistics_Dimension_Creation")]
    partial class MachineIdentifier_Statistics_Dimension_Creation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Statistics.Dimensions", b =>
                {
                    b.Property<int>("DimensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("StatisticId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DimensionId");

                    b.HasIndex("StatisticId");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("Statistics.Model.MachineIdentifier", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MachineId");

                    b.ToTable("MachineIdentifiers");
                });

            modelBuilder.Entity("Statistics.Statistics", b =>
                {
                    b.Property<long>("StatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("StatisticType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StatisticId");

                    b.HasIndex("MachineId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Statistics.Dimensions", b =>
                {
                    b.HasOne("Statistics.Statistics", "Statistics")
                        .WithMany("Dimensions")
                        .HasForeignKey("StatisticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("Statistics.Statistics", b =>
                {
                    b.HasOne("Statistics.Model.MachineIdentifier", "MachineIdentifier")
                        .WithMany("Statistics")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineIdentifier");
                });

            modelBuilder.Entity("Statistics.Model.MachineIdentifier", b =>
                {
                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("Statistics.Statistics", b =>
                {
                    b.Navigation("Dimensions");
                });
#pragma warning restore 612, 618
        }
    }
}
